export const defaults = {first:'',last:'',title:'',company:'',email:'',phone:'',website:'',linkedin:'',bio:'',photo:'',logo:'',accent:'#ffd100',theme:'light',qrMode:'url',destinationMode:'folder',repositoryOwner:'quiksoft',repository:'vCard-Studio',folder:'',githubUser:'',cardName:'',publicUrl:'https://quiksoft.github.io/vCard-Studio/Vcard-yournamehere/',caption:"Let's connect!",qrLogo:false};
export const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeURL(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}
export const slug = d => (`${d.first}-${d.last}`.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'') || 'contact');
const esc = s => String(s || '').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
function fold(line){let result='',bytes=0;for(const c of line){const n=new TextEncoder().encode(c).length;if(bytes+n>75){result+='\r\n ';bytes=1;}result+=c;bytes+=n;}return result;}
export function vcard(d,photo=true){const lines=['BEGIN:VCARD','VERSION:3.0',`N:${esc(d.last)};${esc(d.first)};;;`,`FN:${esc(`${d.first} ${d.last}`.trim())}`];for(const [key,value] of [['ORG',d.company],['TITLE',d.title],['EMAIL;TYPE=INTERNET',d.email],['TEL;TYPE=CELL',d.phone],['URL',safeURL(d.website)],['X-SOCIALPROFILE;TYPE=linkedin',safeURL(d.linkedin)],['NOTE',d.bio]])if(value)lines.push(`${key}:${esc(value)}`);if(photo && d.photo.startsWith('data:image/jpeg;base64,'))lines.push('PHOTO;ENCODING=b;TYPE=JPEG:'+d.photo.split(',')[1]);lines.push('END:VCARD');return lines.map(fold).join('\r\n')+'\r\n';}
export function githubCardURL(user,name){user=user.trim();name=name.trim();if(!/^[a-z0-9](?:[a-z0-9-]{0,37}[a-z0-9])?$/i.test(user)||user.includes('--')||!name)return '';const card=name.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return card?`https://${user.toLowerCase()}.github.io/vcard-${card}`:'';}
export function qrSVG(d){d=syncDestination({...d});const payload=safeURL(d.publicUrl);if(!payload)throw Error('Enter a complete http:// or https:// address for your published card.');const code=new QRCode({content:payload,padding:4,width:1000,height:1000,ecl:'H',color:'#222222',join:true,container:'svg-viewbox',xmlDeclaration:false});let svg=code.svg();const unit=1000/(code.qrcode.modules.length+8);let finders='';for(const [col,row] of [[0,0],[code.qrcode.modules.length-7,0],[0,code.qrcode.modules.length-7]]){const x=(col+4)*unit,y=(row+4)*unit;finders+=`<rect x="${x}" y="${y}" width="${7*unit}" height="${7*unit}" fill="white"/><rect x="${x}" y="${y}" width="${7*unit}" height="${7*unit}" rx="${1.5*unit}" fill="#222222"/><rect x="${x+unit}" y="${y+unit}" width="${5*unit}" height="${5*unit}" rx="${.65*unit}" fill="white"/><rect x="${x+2*unit}" y="${y+2*unit}" width="${3*unit}" height="${3*unit}" rx="${.55*unit}" fill="#222222"/>`;}
if(d.qrLogo&&d.logo)finders+=`<rect x="400" y="455" width="200" height="90" rx="8" fill="white"/><image href="${d.logo}" x="410" y="465" width="180" height="70" preserveAspectRatio="xMidYMid meet"/>`;return svg.replace('</svg>',finders+'</svg>');}
export function qrPosterSVG(d){const qr=qrSVG(d).replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');const height=d.caption?1320:1100;const fontSize=Math.min(80,1700/Math.max(1,d.caption.length));return `<svg xmlns="http://www.w3.org/2000/svg" width="1100" height="${height}" viewBox="0 0 1100 ${height}"><rect width="1100" height="${height}" rx="130" fill="#222222"/><rect x="45" y="45" width="1010" height="1010" rx="86" fill="white"/><defs><clipPath id="qr-panel"><rect x="45" y="45" width="1010" height="1010" rx="86"/></clipPath></defs><g clip-path="url(#qr-panel)"><g transform="translate(45 45) scale(1.01)">${qr}</g></g>${d.caption?'<text x="550" y="1205" text-anchor="middle" fill="white" font-family="Arial,sans-serif" font-size="'+fontSize+'" font-weight="700">'+escapeHTML(d.caption)+'</text>':''}</svg>`;}
export function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export function ink(hex){const rgb=hex.slice(1).match(/../g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>.179?'#202020':'#ffffff';}
export const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({email:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',phone:'<path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .3 2 .7 2.9a2 2 0 0 1-.5 2.1L8 10a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5c.9.4 1.9.6 2.9.7a2 2 0 0 1 1.7 2Z"/>',website:'<path d="m10 13 4-4m-6 6-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m4 2 2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0" transform="translate(1 0)"/>',linkedin:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 10v7m0-10v.1M11 17v-7m0 3a3 3 0 0 1 6 0v4"/>',save:'<circle cx="9" cy="7" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0m4-7v8m-3-3 3 3 3-3"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',back:'<path d="M19 12H5m5-5-5 5 5 5"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4m-4 5v2"/>'})[name]||''}</svg>`;
export function cardMarkup(d,demo=false){const e=escapeHTML,name=`${d.first} ${d.last}`.trim()||(demo?'Your name':'Contact');const links=[['email',d.email,`mailto:${d.email}`],['phone',d.phone,`tel:${d.phone}`],['website',d.website,safeURL(d.website)],['linkedin',d.linkedin,safeURL(d.linkedin)]];return `<article class="contact-card ${d.theme==='dark'?'dark':''}" style="--accent:${d.accent};--ink:${ink(d.accent)}"><div class="card-banner">${d.logo?`<img src="${d.logo}" alt="Company logo">`:'<span>Your logo</span>'}</div><div class="card-body"><div class="avatar">${d.photo?`<img src="${d.photo}" alt="${e(name)}">`:e((d.first[0]||'Y')+(d.last[0]||'N'))}</div><h2>${e(name)}</h2><p>${e(d.title||(demo?'Job title':''))}</p><p class="company">${e(d.company||(demo?'Company':''))}</p><a class="save-contact" download="${slug(d)}.vcf" href="data:text/vcard;charset=utf-8,${encodeURIComponent(vcard(d))}">${icon('save')} Save contact</a><div class="contact-links">${links.filter(([,value,url])=>value&&url).map(([key,value,url])=>`<a href="${e(url)}" ${['website','linkedin'].includes(key)?'target="_blank" rel="noopener"':''}>${icon(key)}<span>${e(value)}</span></a>`).join('')}</div><p class="bio">${e(d.bio||"Let's keep in touch.")}</p></div></article>`;}
export async function imageData(file,kind){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Choose a PNG, JPEG or WebP image.');if(file.size>10*1024*1024)throw Error('Please choose an image smaller than 10 MB.');const bitmap=await createImageBitmap(file);const c=document.createElement('canvas');const size=kind==='photo'?480:640;const ratio=Math.min(1,size/Math.max(bitmap.width,bitmap.height));c.width=Math.max(1,Math.round(bitmap.width*ratio));c.height=Math.max(1,Math.round(bitmap.height*ratio));const ctx=c.getContext('2d');if(kind==='photo'){ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);}ctx.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();return c.toDataURL(kind==='photo'?'image/jpeg':'image/png',.88);}

export function repositoryPagesURL(owner,repo,reported=''){if(!/^[a-z0-9-]+$/i.test(owner)||! /^[a-z0-9][a-z0-9._-]*$/i.test(repo))throw Error('Enter a valid repository owner and repository name.');if(reported){const u=new URL(reported);if(u.protocol!=='https:')throw Error('The hosting address must use HTTPS.');if(!u.hostname.endsWith('.github.io'))return u.href.replace(/\/?$/,'/');}return 'https://'+owner.toLowerCase()+'.github.io/'+(repo.toLowerCase()===owner.toLowerCase()+'.github.io'?'':repo+'/');}
export function effectiveFolder(d){return d.folder||'Vcard-'+(d.first?slug(d):'yournamehere');}
export function syncDestination(d){if(d.destinationMode==='folder'){const folder=effectiveFolder(d);if(!/^Vcard-[a-z0-9][a-z0-9-]{0,80}$/.test(folder)||folder.endsWith('-'))throw Error('Use a folder such as Vcard-jjvlebon, with lowercase letters, numbers and hyphens after Vcard-.');d.publicUrl=repositoryPagesURL(d.repositoryOwner,d.repository)+folder+'/';}return d;}
export function migrateDestination(d,original){if(!original.destinationMode){try{const u=new URL(original.publicUrl);const parts=u.pathname.split('/').filter(Boolean);if(u.hostname==='quiksoft.github.io'&&/^vcard-/i.test(parts.at(-1)||'')){d.destinationMode='folder';d.repositoryOwner='quiksoft';d.repository='vCard-Studio';d.folder='Vcard-'+parts.at(-1).slice(6);}else if(original.publicUrl&&original.publicUrl!=='https://githubuser.github.io/vcard-yournamehere')d.destinationMode='custom';}catch{}}if(!['folder','custom'].includes(d.destinationMode))d.destinationMode='folder';return syncDestination(d);}
