import {manualHTML,manualText} from './manual.js?v=20260909-prefix1';
import {syncDestination,defaults,cardMarkup,escapeHTML,qrSVG,qrPosterSVG,slug,vcard,download} from './core.js?v=20260909-prefix1';
export async function pageHTML(d){const css=await fetch(new URL('./styles.css',import.meta.url)).then(r=>{if(!r.ok)throw Error('Could not load card styles.');return r.text();});return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHTML(d.first+' '+d.last)} — Digital business card</title><style>${css}</style></head><body class="standalone">${cardMarkup(d)}</body></html>`;}
export async function png(d){const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(qrPosterSVG(d));await img.decode();const c=document.createElement('canvas');c.width=1100;c.height=d.caption?1320:1100;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('Could not render QR image.')),'image/png'));}
// Uncompressed ZIP writer: no network, build step, or third-party archive dependency.
export function zip(files){const encoder=new TextEncoder();let offset=0;const chunks=[],central=[];const u16=(a,o,v)=>new DataView(a.buffer).setUint16(o,v,true),u32=(a,o,v)=>new DataView(a.buffer).setUint32(o,v>>>0,true);for(const [name,text] of Object.entries(files)){const n=encoder.encode(name),data=text instanceof Uint8Array?text:encoder.encode(text);let crc=0xffffffff;for(const b of data){crc^=b;for(let k=0;k<8;k++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}crc=(crc^0xffffffff)>>>0;const h=new Uint8Array(30+n.length);u32(h,0,0x04034b50);u16(h,4,20);u16(h,6,0x800);u32(h,14,crc);u32(h,18,data.length);u32(h,22,data.length);u16(h,26,n.length);h.set(n,30);const c=new Uint8Array(46+n.length);u32(c,0,0x02014b50);u16(c,4,20);u16(c,6,20);u16(c,8,0x800);u32(c,16,crc);u32(c,20,data.length);u32(c,24,data.length);u16(c,28,n.length);u32(c,42,offset);c.set(n,46);chunks.push(h,data);central.push(c);offset+=h.length+data.length;}const end=new Uint8Array(22);u32(end,0,0x06054b50);u16(end,8,central.length);u16(end,10,central.length);u32(end,12,central.reduce((n,c)=>n+c.length,0));u32(end,16,offset);return new Blob([...chunks,...central,end],{type:'application/zip'});}
export async function exportCard(d,kind){const name=slug(d);if(kind==='vcf')download(vcard(d),name+'.vcf','text/vcard;charset=utf-8');if(kind==='svg')download(qrPosterSVG(d),name+'-qr.svg','image/svg+xml');if(kind==='png')download(await png(d),name+'-qr.png','image/png');if(kind==='html')download(await pageHTML(d),name+'.html','text/html');if(kind==='zip')download(zip(await cardFiles(d)),name+'-website.zip','application/zip');}

export function editableCard(d){return Object.fromEntries(Object.keys(defaults).map(k=>[k,typeof d[k]===typeof defaults[k]?d[k]:defaults[k]]));}
export async function cardFiles(d){d=syncDestination({...d});return {'index.html':await pageHTML(d),'contact.vcf':vcard(d),'qr.svg':qrPosterSVG(d),'qr.png':new Uint8Array(await (await png(d)).arrayBuffer()),[slug(d)+'-draft.json']:JSON.stringify(editableCard(d),null,2),'card.json':JSON.stringify({format:'vcard-studio-1',card:editableCard(d)},null,2),'USER-MANUAL.html':manualHTML(d),'USER-MANUAL.txt':manualText(d),'.nojekyll':'','README.md':`# Digital business card

Published URL: ${d.publicUrl}

Open USER-MANUAL.html for phone and wallet instructions. card.json contains the public editable card data, including images; it contains no credentials. Keep all files together when uploading.
`};}
