import {escapeHTML as e,slug,hostingSettings,effectiveFolder} from './core.js?v=20260909-prefix1';
import {cardFiles} from './export.js?v=20260909-prefix1';
import {githubClient} from './github.js?v=20260909-prefix1';
import {repositorySnapshot,reviewFolder,readPublishedCard,publishFolder} from './folder-github.js?v=20260909-prefix1';
function context(){const match=location.hostname.match(/^([a-z0-9-]+)\.github\.io$/i);return {owner:match?.[1]||'quiksoft',repo:location.pathname.split('/').filter(Boolean)[0]||'vCard-Studio'};}
export function openFolderManager({card,target=null,load=false,onLoad,onPublished}){if(location.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(location.hostname))throw Error('Use HTTPS or localhost to connect GitHub.');const settings=hostingSettings();const initial={owner:settings.githubOwner,repo:settings.githubRepository};const dialog=document.createElement('dialog');dialog.className='publish-dialog';dialog.innerHTML=`<h2>${load?'Edit a published card':target?'Update published card':'Publish to a card folder'}</h2><form><div class="form-grid" id="folder-inputs"><label class="field">Repository owner<input id="folder-owner" required value="${e(initial.owner)}" readonly></label><label class="field">Repository name<input id="folder-repo" required value="${e(initial.repo)}" readonly></label>${load?'':`<label class="field wide">Card folder<input id="folder-name" required value="${e(target?.folder||effectiveFolder(card))}" readonly></label>`}<label class="field wide">GitHub token<input id="folder-token" type="password" autocomplete="off" required spellcheck="false"></label><p class="hint wide">Select only this repository in a short-lived fine-grained token. Set Contents to Read and write and Pages to Read. No Administration permission is needed. The token is sent only to GitHub and cleared when this dialog closes.</p><a class="hint" href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">Create token</a></div><div id="folder-review"></div><p id="folder-status" role="status" aria-live="polite"></p><div class="dialog-actions"><button type="button" class="secondary" id="folder-close">Cancel</button><button class="primary" id="folder-submit">${load?'Find published cards':'Review publication'}</button></div></form>`;document.body.append(dialog);dialog.showModal();const q=s=>dialog.querySelector(s);let api=null,plan=null,snapshot=null,files=null,busy=false,done=false;
function close(){if(busy)return;api=null;files=null;q('#folder-token').value='';dialog.close();dialog.remove();}q('#folder-close').onclick=close;dialog.addEventListener('cancel',ev=>{ev.preventDefault();close();});
dialog.querySelector('form').onsubmit=async ev=>{ev.preventDefault();if(busy||done)return;busy=true;q('#folder-submit').disabled=true;q('#folder-close').disabled=true;let shouldClose=false;try{if(!api){const token=q('#folder-token').value.trim();if(!/^github_pat_[a-zA-Z0-9_]+$/.test(token))throw Error('Enter a fine-grained GitHub token, not your password.');api=githubClient(token);}
if(load){if(!snapshot){snapshot=await repositorySnapshot(api,q('#folder-owner').value.trim(),q('#folder-repo').value.trim());const folders=snapshot.entries.filter(x=>x.type==='tree'&&x.path.startsWith(settings.folderPrefix));if(!folders.length)throw Error('No Vcard- folders found. Publish a card folder first.');q('#folder-review').innerHTML=`<label class="field">Published card<select id="folder-choice">${folders.map(x=>`<option>${e(x.path)}</option>`).join('')}</select></label><p class="hint">Loading replaces the current editor draft. Download your draft first if you need to keep it. Cards must include card.json created by this version.</p>`;q('#folder-submit').textContent='Load into editor';}else{const result=await readPublishedCard(api,snapshot,q('#folder-choice').value);onLoad(result.card,result.target,result.url);shouldClose=true;}}
else if(!plan){const checked=await reviewFolder(api,q('#folder-owner').value.trim(),q('#folder-repo').value.trim(),q('#folder-name').value.trim(),target);files=await cardFiles({...card,urlName:checked.folder.slice(settings.folderPrefix.length),folder:checked.folder,publicUrl:checked.url});plan=checked;q('#folder-review').innerHTML=`<p><strong>${plan.update?'Update':'Create'} ${e(plan.owner+'/'+plan.repo+'/'+plan.folder)}</strong></p><p>URL: <strong>${e(plan.url)}</strong></p><p>This publishes your contact page, QR images, manual and editable card data. Details and images will be public. Other card folders and app files are preserved.</p><label class="checkbox"><input type="checkbox" required> I approve ${plan.update?'updating this published card':'publishing this card'} publicly.</label>`;q('#folder-submit').textContent=plan.update?'Update public card':'Publish public card';}
else{const result=await publishFolder(api,plan,files,msg=>q('#folder-status').textContent=msg);api=null;files=null;onPublished(result.url,{owner:plan.owner,repo:plan.repo,folder:plan.folder,folderSHA:result.folderSHA});done=true;q('#folder-review').innerHTML=`<h3>Card committed</h3><p>Your repository deployment will publish this change. It may take a few minutes. Your URL, QR code and downloadable package now use the folder address.</p><p><a href="${e(result.url)}" target="_blank" rel="noopener noreferrer">Open card</a> · <a href="${e(result.repositoryURL+'/actions')}" target="_blank" rel="noopener noreferrer">Check deployment</a></p><p class="hint">The updated build.mjs must be installed in this repository to include Vcard- folders. A successful commit does not mean the live deployment has finished.</p>`;q('#folder-submit').hidden=true;q('#folder-close').textContent='Done';q('#folder-status').textContent='Saved to GitHub. Token cleared.';}
if(plan||snapshot){q('#folder-token').value='';q('#folder-inputs').hidden=true;for(const input of q('#folder-inputs').querySelectorAll('input'))input.disabled=true;}}
catch(error){q('#folder-status').textContent=error.message;if(plan||snapshot){done=true;api=null;files=null;q('#folder-submit').hidden=true;q('#folder-close').textContent='Close';q('#folder-status').textContent+=' If the commit request timed out, inspect GitHub before retrying.';}else{api=null;snapshot=null;q('#folder-token').value='';}}
finally{busy=false;q('#folder-submit').disabled=false;q('#folder-close').disabled=false;if(shouldClose)close();}};
}
